import {
  WiDaySunny,
  WiNightSleet,
  WiDayCloudy,
  WiDayCloudyHigh,
  WiHot,
  WiDaySleetStorm,
  WiRainWind,
  WiDaySunnyOvercast,
  WiNightClear,
  WiNightCloudy,
} from "weather-icons-react";

const FORECASTS = [
  {
    city: "Lisbon",
    temp: "21°C",
    icon: WiDaySunny,
    flexBasis: "50%",
    backgroundColor: "#70b8db",
    hoverBackgroundColor: "#3399cc",
  },
  {
    city: "Paris",
    temp: "11°C",
    icon: WiNightSleet,
    flexBasis: "25%",
    backgroundColor: "#70dbdb",
    hoverBackgroundColor: "#33cccc",
  },
  {
    city: "Belgrade",
    temp: "15°C",
    icon: WiDayCloudy,
    flexBasis: "25%",
    backgroundColor: "#b894b8",
    hoverBackgroundColor: "#996699",
  },
  {
    city: "Venice",
    temp: "21°C",
    icon: WiDayCloudyHigh,
    flexBasis: "25%",
    backgroundColor: "#c46767",
    hoverBackgroundColor: "#cc3333",
  },
  {
    city: "Tel-Aviv",
    temp: "32°C",
    icon: WiHot,
    flexBasis: "25%",
    backgroundColor: "#eb9580",
    hoverBackgroundColor: "#e2674a",
  },
  {
    city: "Cair",
    temp: "21°C",
    icon: WiDaySunny,
    flexBasis: "25%",
    backgroundColor: "#ffdb94",
    hoverBackgroundColor: "#ffcc66",
  },
  {
    city: "New-York",
    temp: "17°C",
    icon: WiDaySleetStorm,
    flexBasis: "25%",
    backgroundColor: "#b8dbb8",
    hoverBackgroundColor: "#99cc99",
  },
  {
    city: "New-Delhi",
    temp: "17°C",
    icon: WiRainWind,
    flexBasis: "25%",
    backgroundColor: "#94b8b8",
    hoverBackgroundColor: "#669999",
  },
  {
    city: "San-Francisco",
    temp: "15°C",
    icon: WiDaySunnyOvercast,
    flexBasis: "50%",
    backgroundColor: "#db94b8",
    hoverBackgroundColor: "#cc6699",
  },
  {
    city: "Tokyo",
    temp: "8°C",
    icon: WiNightClear,
    flexBasis: "25%",
    backgroundColor: "#70b894",
    hoverBackgroundColor: "#339966",
  },
  {
    city: "Sydney",
    temp: "25°C",
    icon: WiNightCloudy,
    flexBasis: "100%",
    backgroundColor: "#9494b8",
    hoverBackgroundColor: "#666699",
  },
];

export default FORECASTS;
